### ISSUE TITLE
CircuitPython support

### ISSUE THREAD

**Issue by codegrue** [turfptax/ugit#14]
Any plans to port this to CircuitPython?

**Comment by turfptax** [comment]
I will take a look this weekend.

Circuit python has different built-in modules but it shouldn't be difficult to modify this code for it.

Maybe someone more devoted wants to branch this for circuit python development. If not I would be happy to try my best to keep it working on both micropython and circuit python. Maybe adafruit might want to chime in :D.

**Comment by turfptax** [comment]
> Any plans to port this to CircuitPython?

As I am unfamiliar with how to implement a Circuit Python version of this I will have to close this. If anyone is willing to help feel free to chime in.
