### ISSUE TITLE
ESP32 OSError: 20

### ISSUE THREAD

**Issue by csflakkee** [turfptax/ugit#18]
Without changing anything except for the wifi ssid + password I get this error
I tried it with the following generic ota firmware: 
[v1.19.1 (2022-06-18) .bin](https://micropython.org/resources/firmware/esp32-ota-20220618-v1.19.1.bin)
it also occurs with: https://micropython.org/resources/firmware/esp32-ota-20230203-unstable-v1.19.1-852-g9ea64a36a.bin

The board I am using is esp32 devkit v1

--------------------------------------
Local Ip Address, Subnet Mask, Default Gateway, Listening on...
('192.168.1.216', '255.255.255.0', '192.168.1.1', '192.168.1.1')
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "ugit.py", line 67, in pull_all
  File "ugit.py", line 126, in build_internal_tree
  File "ugit.py", line 131, in add_to_tree
OSError: 20

**Comment by turfptax** [comment]
Do you have a file that is blank on the board?

Also, have you restarted the REPL environment and also hard rebooted the board after the change of ugit.py?

**Comment by csflakkee** [comment]
@turfptax thank you for the quick reply.

I only have boot.py and the ugit.py on the board 

boot.py contains:
-----------
import ugit
ugit.pull_all()
-------------

Current micropython version on the board is 
MicroPython v1.19.1 on 2022-06-18; 4MB/OTA module with ESP32
Type "help()" for more information.

**Comment by turfptax** [comment]
> @turfptax thank you for the quick reply.
> 
> The magic was in the hard reboot
> 
> import machine machine.reset() was obviously not sufficient !

Wonderful!

I've been tracking a memory issue with REPL and 1.19 firmware and this usually does the trick!
