### ISSUE TITLE
OSError 20

### ISSUE THREAD

**Issue by Kevinvincentals** [turfptax/ugit#19]
Traceback (most recent call last):
  File "boot.py", line 3, in <module>
  File "ugit.py", line 67, in pull_all
  File "ugit.py", line 126, in build_internal_tree
  File "ugit.py", line 131, in add_to_tree
OSError: 20

I'm actually unsure if this is an issue of ugit itself, or rather me. Can you please let me know what can be done to resolve this ?:-)

Kudos on the project!

**Comment by Kevinvincentals** [comment]
Use: like ugit.wificonnect(SSID,Password)
otherwise uses ssid,password in top of ugit.py code
Wifi Connected!!
SSID: Yeet
Local Ip Address, Subnet Mask, Default Gateway, Listening on...
('192.168.0.29', '255.255.255.0', '192.168.0.1', '192.168.0.1')
boot.py
sub_path: /boot.py
/boot.py
ugit.py
sub_path: /ugit.py
/ugit.py
 ignore removed ----------------------
['/boot.py']
Traceback (most recent call last):
  File "boot.py", line 18, in <module>
  File "ugit.py", line 73, in pull_all
KeyError: tree
MicroPython v1.19.1 on 2022-06-18; ESP32 module with ESP32
Type "help()" for more information.


Seems to be the new error now.

**Comment by Kevinvincentals** [comment]
Just as info.
Tested on both open and closed repo. The repo im testing is:
https://github.com/Kevinvincentals/esp32_test
Wifi Connected!!
SSID: Yeet
Local Ip Address, Subnet Mask, Default Gateway, Listening on...
('192.168.0.29', '255.255.255.0', '192.168.0.1', '192.168.0.1')
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "ugit.py", line 67, in pull_all
  File "ugit.py", line 126, in build_internal_tree
  File "ugit.py", line 131, in add_to_tree
OSError: 20


If I do the same on your test repo, it downloads it just fine. Am I missing something?

**Comment by turfptax** [comment]
Are you running this on a python repository?

Also your url for your github gives a 404 error for esp32_test. I think that is your error.

**Comment by Kevinvincentals** [comment]
Hi.
I Got it working in the end - seemed to be Some path issues with main/master

Idk if its caching, but if I push something, and the esp32 makes a pull, it has to rerun the pull 3-4 times before the new files are actually retrieved.

Is it a caching issue?


> Are you running this on a python repository?
> 
> 
> 
> Also your url for your github gives a 404 error for esp32_test. I think that is your error.
> 
> 
> 
> 
> 
> 
> 
>
