### ISSUE TITLE
Private repository

### ISSUE THREAD

**Issue by progressify** [turfptax/ugit#6]
Is possible to include private repository with github token authentication?

**Comment by turfptax** [comment]
Token authentication is not built in but I will give it a look.  https://stackoverflow.com/questions/17622439/how-to-use-github-api-token-in-python-for-requesting

Looks relatively easy to implement. I'll give it a shot here and push it to the dev branch.

**Comment by turfptax** [comment]
> Is possible to include private repository with github token authentication?
There are some issues with the SSL but I will work on this weekend.

We will need to add the 'Authorization' header with the value token.

{'Authorization' = 'token %s' % self.api_token} Since we already have 1 header value we will have to add this to the header so the header dict object will have two elements.

**Comment by nolansingroy** [comment]
> > Is possible to include private repository with github token authentication?
> > There are some issues with the SSL but I will work on this weekend.
> 
> We will need to add the 'Authorization' header with the value token.
> 
> {'Authorization' = 'token %s' % self.api_token} Since we already have 1 header value we will have to add this to the header so the header dict object will have two elements.

does this private repo feature work now?

**Comment by turfptax** [comment]
> > > Is possible to include private repository with github token authentication?
> > > There are some issues with the SSL but I will work on this weekend.
> > 
> > 
> > We will need to add the 'Authorization' header with the value token.
> > {'Authorization' = 'token %s' % self.api_token} Since we already have 1 header value we will have to add this to the header so the header dict object will have two elements.
> 
> does this private repo feature work now?

No,

I am actively developing it on the dev branch. I will update the code tomorrow after testing on these three boards: ESP32 S2 Mini, ESP32 C3 mini, ESP8266.
